// <auto-generated />
namespace ApertureCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Settings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Settings));
        
        string IMigrationMetadata.Id
        {
            get { return "201308272056447_Settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
